server.port=8082

# Conexión H2 en memoria (Se reinicia limpia cada vez que ejecutas el proyecto)
spring.datasource.url=jdbc:h2:mem:productosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Crea las tablas limpias desde cero en cada reinicio
spring.jpa.hibernate.ddl-auto=create-drop
spring.h2.console.enabled=true

# Azure AD
azure.ad.jwk-set-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/discovery/v2.0/keys
azure.ad.issuer=https://sts.windows.net/abf8edad-bd14-425d-9255-2e0e7e57dfa2/
azure.ad.audience=api://9078dcc3-9503-4237-a463-d5a4a96cb61f

# Inicialización de SQL
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always