==========================================
Configuración del Microservicio Pedidos
==========================================
spring.application.name=ms-pedidos
server.port=8081

==========================================
Conexión a MySQL (EC2)
==========================================
spring.datasource.url=jdbc:mysql://52.0.242.49:3306/pedidos_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=appuser
spring.datasource.password=TuPasswordSegura123!

==========================================
Configuración Hibernate / JPA
==========================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

==========================================
Azure AD JWT / Seguridad
==========================================
azure.ad.jwk-set-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/discovery/v2.0/keys
azure.ad.issuer=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/v2.0
azure.ad.audience=api://9078dcc3-9503-4237-a463-d5a4a96cb61f
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/discovery/v2.0/keys

==========================================
Inicialización de SQL
==========================================
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=never