spring.application.name=ms-rabbit-admin
server.port=8085

azure.ad.jwk-set-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/discovery/v2.0/keys
azure.ad.issuer=https://sts.windows.net/abf8edad-bd14-425d-9255-2e0e7e57dfa2/
azure.ad.audience=api://9078dcc3-9503-4237-a463-d5a4a96cb61f
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://login.microsoftonline.com/abf8edad-bd14-425d-9255-2e0e7e57dfa2/discovery/v2.0/keys